# Generated by Django 3.0.6 on 2020-06-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tab_title',
            field=models.CharField(default='A Golden Fern', max_length=255),
        ),
    ]
