# Generated by Django 3.0.6 on 2020-09-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_issues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
