# Generated by Django 3.0.6 on 2020-09-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20200912_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='body',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tab_title',
        ),
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(default='Issue', max_length=255),
        ),
    ]
