# Generated by Django 3.0.6 on 2020-09-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_auto_20200912_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='parallaximage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
