# Generated by Django 3.0.6 on 2020-09-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_issue_parallaximage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='parallaximage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
