# Generated by Django 3.0.6 on 2020-09-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20200912_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='color',
            field=models.CharField(default='white', max_length=255),
            preserve_default=False,
        ),
    ]
